Ensure gutter icons show up in the correct locations
dafny-lang/ide-vscode pull request #241
Opened 2022-08-03 15:01 UTC by keyboardDrummer

Fixes https://github.com/dafny-lang/ide-vscode/issues/237

There's seems to be a bug caused by `commands.executeCommand('vscode.executeDocumentSymbolProvider', uri)` [here](https://github.com/dafny-lang/ide-vscode/blob/master/src/ui/verificationSymbolStatusView.ts#L184) not returning the expected results, possibly because it's returning results for a different document version that the one we're expected. This PR no longer uses results from `commands.executeCommand('vscode.executeDocumentSymbolProvider', uri)` to compute the linesToSkip for gutter icons, this both avoid the bug from #237 and makes the gutter icons show up faster since there's no extra LSP server roundtrip involved.

2022-08-03 15:15 UTC, MikaelMayer commented
> Fixes #237

Thanks for trying ! However, I just tested this PR, I have the same problem (I pressed three times ENTER, this is what I got the first time)

![image](https://user-images.githubusercontent.com/3601079/182644553-374bc50e-800a-480a-a633-a854f1455b8f.png)

2022-08-04 13:00 UTC, keyboardDrummer commented
> Thanks for trying ! However, I just tested this PR, I have the same problem (I pressed three times ENTER, this is what I got the first time)

I wasn't able to reproduce that, but I also made some more changes to improve the behavior of the play icon.

2022-08-04 15:15 UTC, MikaelMayer commented
> I wasn't able to reproduce that, but I also made some more changes to improve the behavior of the play icon.

Just tried your new version, this bug seems indeed harder to obtain, but by writing two methods, and long-pressing and short-pressing enter, I get similar overlaps
![image](https://user-images.githubusercontent.com/3601079/182882978-3db435b6-e675-4e1e-b326-2e67e2d09f16.png)

2022-08-04 15:18 UTC, MikaelMayer commented
> > I wasn't able to reproduce that, but I also made some more changes to improve the behavior of the play icon.
> 
> Just tried your new version, this bug seems indeed harder to obtain, but by writing two methods, and long-pressing and short-pressing enter, I get similar overlaps ![image](https://user-images.githubusercontent.com/3601079/182882978-3db435b6-e675-4e1e-b326-2e67e2d09f16.png)

What is worse than that, is that an incorrect state in the language server seems to persist when I create a new unrelated document, I get this:

![image](https://user-images.githubusercontent.com/3601079/182884178-8bab05ec-75f2-4dc6-b016-ee2b4b13e2ea.png)

2022-08-09 16:00 UTC, MikaelMayer requested changes
A few changes, otherwise, looks good ! I wasn't able to reproduce the bugs that this PR claims to fix, great job.

2022-08-10 09:06 UTC, keyboardDrummer commented on src/ui/verificationSymbolStatusView.ts
> +    }, this, context.subscriptions);
`workspace.onDidCloseTextDocument` creates a disposable, and without passing these arguments that disposable is never disposed.

2022-08-10 17:00 UTC, MikaelMayer approved these changes
Thank you for making this extension configurable. Since it's now integrated in the back-end though, I suspect deactivating it won't prevent any errors though.

2022-08-10 17:14 UTC, merged